VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.network "public_network"

  ### ports allowing external access to app services inside the box:
  # Apache Httpd
  config.vm.network :forwarded_port, guest: 30000, host: 30000
  # EAP and other backends
  config.vm.network :forwarded_port, guest: 30080, host: 30080
  # MySQL
  config.vm.network :forwarded_port, guest: 30306, host: 30306

  config.vm.define "do080host" do |do080host|
    do080host.vm.box = "rhel-7.2" 
    do080host.vm.hostname = "do080host.example.com"
    do080host.vm.synced_folder ".", "/vagrant", disabled: false
    do080host.vm.provision "shell", path: "reg.sh", run: "always"
    do080host.vm.provision "shell", path: "install.sh"
    do080host.vm.provider "virtualbox" do |vbox|
      vbox.name = "DO080host"
      vbox.memory = 4096
      vbox.cpus = 2
      vbox.customize ["modifyvm", :id, "--vram", "32"]
    end
  end
end
