apiVersion: v1
kind: Pod
metadata:
  name: wildfly 
  labels: 
    name: wildfly
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: do080/todojee
      imagePullPolicy: IfNotPresent
      name: wildfly 
      ports: 
        - containerPort: 8080 
          name: wildfly 
      env:
        - name: MYSQL_ENV_MYSQL_DATABASE
          value: items
        - name: MYSQL_ENV_MYSQL_USER
          value: user1
        - name: MYSQL_ENV_MYSQL_PASSWORD
          value: mypa55
